Users should be able to make Return trip - WIP
andela/northstar-backend pull request #32
Opened 2019-08-29 11:03 UTC by oleesir

What does this PR do?
Implement ft-create-round-trips-167727460

Description of Task to be completed?
```POST/api/v1/requests```

How should this be manually tested?
Use postman to test endpoint above with this header:
key:Content-Type value: application/json

What are the relevant pivotal tracker stories?
[#167727460](https://www.pivotaltracker.com/story/show/167727460)

Any background context you want to add?
N/A

Screenshots
N/A

2019-09-02 10:24 UTC, parkerthegeniuschild reviewed
I am trying to checkout this branch but I have no idea what my POST body should contain.

Please elucidate. Thank you.

2019-09-02 10:31 UTC, oleesir commented
> I am trying to checkout this branch but I have no idea what my POST body should contain.
> 
> Please elucidate. Thank you.



> I am trying to checkout this branch but I have no idea what my POST body should contain.
> 
> Please elucidate. Thank you.

ft-create-round-trips-167727460

2019-09-05 18:52 UTC, parkerthegeniuschild requested changes
[x] Remove local LOGS from version control
---
![image](https://user-images.githubusercontent.com/51248761/64370580-a35ab700-d016-11e9-82c9-f5891d039150.png)
---
![image](https://user-images.githubusercontent.com/51248761/64370608-b077a600-d016-11e9-8244-ed144b5b0297.png)

2019-09-05 19:43 UTC, parkerthegeniuschild approved these changes

2019-09-08 15:23 UTC, merged