#167727461 Make Multi-City Trip Requests
andela/northstar-backend pull request #41
Opened 2019-09-02 12:58 UTC by G-Chilie

#### What does this PR do?
This allows users to make multi-city trip requests.

#### How should this be manually tested?
Checkout the branch and install the npm dependencies. Use any REST API tool and hit the endpoint: `/POST /api/v1/request/multiCity`
```
category:  multi-city   // must be multi-city
origin: {string}
destination: [array]
departure_date: {string}   // e.g. 02-02-2020
return_date: {string}   // e.g. 03-05-2021
reason: {string}
room_id: {integer}
```
#### Any background context you want to provide?
This route is protected, so you need to be logged in to call it. The token will be pulled from
`Authorization:  <token>`. Make sure to add it there. To make a request, you need a valid `room_id`.

#### What are the relevant pivotal tracker stories?
[#167727461](https://www.pivotaltracker.com/story/show/167727461)

2019-09-02 21:24 UTC, parkerthegeniuschild requested changes
[x] Code does not run
---
![image](https://user-images.githubusercontent.com/51248761/64133684-07d80500-cdd0-11e9-90b5-0b00c50ca5b0.png)

[x] Endeavor to check for linting errors
---
![image](https://user-images.githubusercontent.com/51248761/64133703-22aa7980-cdd0-11e9-8fca-53463d80647e.png)

[x] Typos
---
![image](https://user-images.githubusercontent.com/51248761/64133708-305fff00-cdd0-11e9-84fc-4c7600fdabad.png)

[x] The extra controller not needed.
---
![image](https://user-images.githubusercontent.com/51248761/64133716-3e158480-cdd0-11e9-9f48-a4c9bfc736b5.png)

2019-09-03 07:53 UTC, danndav requested changes
this route was tested fine on my own end, but i also feel this should be done inside the request.controller file instead of creating a new multirequest controller.

2019-09-03 08:07 UTC, G-Chilie commented
> this route was tested fine on my own end, but i also feel this should be done inside the request.controller file instead of creating a new multirequest controller.

Thanks, I will move it to request controller

2019-09-03 11:19 UTC, danndav approved these changes

2019-09-05 14:30 UTC, closed without merging