ft(password reset):user should reset password
andela/northstar-backend pull request #44
Opened 2019-09-03 11:32 UTC by danndav

***What does this PR do?***
Enable a registered user to reset his forgotten password via an email notification

Description of Task to be completed?
- forget password implementation
- receive an email for password reset

***How should this be manually tested?***
clone the repository
npm install
add a .env file with the appropiate content as specified in the .env_sample file
sign up as specified in the swagger docs
go to route localhost:3000/api/v1

/passwordreset and insert your registered mail in the body of the request
An email containing link to reset your password will be delivered to the registered mail 
click on the link to reset your password

Any background context you want to provide?
![Screenshot from 2019-09-03 12-27-37](https://user-images.githubusercontent.com/30337095/64169836-8a031080-ce46-11e9-825e-e784293276ce.png)
***What are the relevant pivotal tracker stories?***
[#166214115](https://www.pivotaltracker.com/story/show/167727456l)

2019-09-03 21:48 UTC, parkerthegeniuschild requested changes
[x] Rename your PR title according to spec.
---
![image](https://user-images.githubusercontent.com/51248761/64211099-fdd00800-ce9c-11e9-81df-ae7a462b661a.png)

2019-09-04 09:29 UTC, danndav commented
> ## [x] Rename your PR title according to spec.
> ![image](https://user-images.githubusercontent.com/51248761/64211099-fdd00800-ce9c-11e9-81df-ae7a462b661a.png)

alright thanks, i have done that

2019-09-05 07:17 UTC, O-Osahon requested changes
Good job bro. Please make those changes while I test the app

2019-09-05 07:17 UTC, O-Osahon commented on src/controllers/user.controller.js
> +        // res.json(data);
NOTHING MUCH: please always try to remove commented-out code before pushing

2019-09-05 07:17 UTC, O-Osahon commented on src/routes/api/auth.router.js
> +router.post('/passwordreset', UserController.resetpasswordEmail);
This url could use an hyphen like so:
` /password-reset`

2019-09-05 17:23 UTC, parkerthegeniuschild commented
So I tried testing again today.

[x] There is no `.env_sample` file to use as a guide.
---
![image](https://user-images.githubusercontent.com/51248761/64336852-e6486a80-cfd5-11e9-8fb3-683d7d011d79.png)
---
[x] Resolve conflicts
---
![image](https://user-images.githubusercontent.com/51248761/64336897-fd875800-cfd5-11e9-9c65-4d9ddfaf9b29.png)
---
[x] Hypenate multi-worded routes
---
![image](https://user-images.githubusercontent.com/51248761/64337027-548d2d00-cfd6-11e9-929d-42d97820effe.png)
---
[x]

2019-09-07 07:48 UTC, parkerthegeniuschild commented
[x] I am going to approve this; although `the email never came.`
---

2019-09-07 07:48 UTC, parkerthegeniuschild approved these changes

2019-09-08 16:24 UTC, O-Osahon approved these changes
Great job!

2019-09-09 11:54 UTC, merged